- name: Get uname
  command: uname -r
  register: os_uname
  changed_when: false

- name: Add APT Docker repo key
  apt_key: keyserver=keyserver.ubuntu.com id={{docker_repo_key}}

- name: Install apt-transport-https package
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    apt-transport-https

- name: Add Docker repo
  apt_repository: repo='deb {{docker_repo}} {{docker_dist}} main' state=present

- name: Install docker-engine package
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - docker-engine

# consider seperate role here
- name: Change ufw forward policy to ACCEPT
  command: sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
  when: docker_listen_tcp == True

- name: Reload ufw
  command: ufw reload
  when: docker_listen_tcp == True

- name: Allow incoming tcp traffic on {{docker_listen_port}}
  command: ufw allow {{docker_listen_port}}/tcp
  when: docker_listen_tcp == True
